// <auto-generated/>
// Shared DTO for Mod Diagnostic Snapshot.
// This file is compiled by both:
//   - MxFramework.Authoring.Core (dotnet CLI, System.Text.Json)
//   - MxFramework.Config.Runtime (Unity, Newtonsoft.Json)
//
// Design rule: No serialization attributes in this file.
// Each consumer configures its own JSON serializer settings (camelCase, etc.).
// Schema consistency is verified by unit tests.

using System.Collections.Generic;

namespace MxFramework.Authoring
{
    /// <summary>
    /// Summary statistics for a mod diagnostic snapshot.
    /// </summary>
    public sealed class ModDiagnosticSummaryDto
    {
        public int Discovered { get; set; }
        public int Valid { get; set; }
        public int Invalid { get; set; }
        public int Enabled { get; set; }
        public int Ordered { get; set; }
        public int Skipped { get; set; }
        public int Overrides { get; set; }
        public int Errors { get; set; }
        public int Warnings { get; set; }
    }

    /// <summary>
    /// Loadout summary: which packages are enabled.
    /// </summary>
    public sealed class ModDiagnosticLoadoutSummaryDto
    {
        public bool IsDefaultAll { get; set; }
        public string ProfileId { get; set; } = string.Empty;
        public string DisplayName { get; set; } = string.Empty;
        public List<string> EnabledPackageKeys { get; set; } = new List<string>();
    }

    /// <summary>
    /// Per-package summary in a diagnostic snapshot.
    /// </summary>
    public sealed class ModDiagnosticPackageSummaryDto
    {
        public string PackageKey { get; set; } = string.Empty;
        public string PackageId { get; set; } = string.Empty;
        public string DisplayName { get; set; } = string.Empty;
        public string Version { get; set; } = string.Empty;
        public string Kind { get; set; } = string.Empty;
        public string ContainerPath { get; set; } = string.Empty;
        public string PackageRelativePath { get; set; } = string.Empty;
        public bool IsValid { get; set; }
        public bool IsEnabled { get; set; }
        public List<string> Errors { get; set; } = new List<string>();
        public List<string> Warnings { get; set; } = new List<string>();
    }

    /// <summary>
    /// A single item in the load plan (ordered or skipped).
    /// </summary>
    public sealed class ModDiagnosticLoadPlanItemDto
    {
        public string PackageKey { get; set; } = string.Empty;
        public string PackageId { get; set; } = string.Empty;
        public string State { get; set; } = string.Empty;
        public string SkipReason { get; set; } = string.Empty;
        public int OrderIndex { get; set; } = -1;
    }

    /// <summary>
    /// An override record: which package wins a conflicting config entry.
    /// </summary>
    public sealed class ModDiagnosticOverrideDto
    {
        public string ConfigType { get; set; } = string.Empty;
        public int Id { get; set; }
        public List<string> PackageChain { get; set; } = new List<string>();
        public string WinnerPackageKey { get; set; } = string.Empty;
        public string WinnerPackageId { get; set; } = string.Empty;
    }

    /// <summary>
    /// A single diagnostic issue (error or warning).
    /// </summary>
    public sealed class ModDiagnosticIssueDto
    {
        public string Severity { get; set; } = string.Empty;
        public string Code { get; set; } = string.Empty;
        public string Source { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
    }

    /// <summary>
    /// Root DTO for the mx.modDiagnosticSnapshot.v1 format.
    /// Shared between Runtime (Unity/Newtonsoft) and CLI (dotnet/System.Text.Json).
    /// No serialization attributes — each side configures its own JSON settings.
    /// </summary>
    public sealed class ModDiagnosticSnapshotDto
    {
        public const string ExpectedFormat = "mx.modDiagnosticSnapshot.v1";

        public string Format { get; set; } = ExpectedFormat;
        public string GeneratedUtc { get; set; } = string.Empty;
        public bool Success { get; set; }
        public ModDiagnosticSummaryDto Summary { get; set; } = new ModDiagnosticSummaryDto();
        public ModDiagnosticLoadoutSummaryDto Loadout { get; set; } = new ModDiagnosticLoadoutSummaryDto();
        public List<ModDiagnosticPackageSummaryDto> Packages { get; set; } = new List<ModDiagnosticPackageSummaryDto>();
        public List<ModDiagnosticLoadPlanItemDto> LoadPlan { get; set; } = new List<ModDiagnosticLoadPlanItemDto>();
        public List<ModDiagnosticOverrideDto> Overrides { get; set; } = new List<ModDiagnosticOverrideDto>();
        public List<ModDiagnosticIssueDto> Errors { get; set; } = new List<ModDiagnosticIssueDto>();
        public List<ModDiagnosticIssueDto> Warnings { get; set; } = new List<ModDiagnosticIssueDto>();
    }
}